apiVersion: apps/v1
kind: Deployment
metadata:
  name: pdf2image
  labels:
    app.kubernetes.io/name: pdf2image
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: pdf2image
  template:
    metadata:
      labels:
        app.kubernetes.io/name: pdf2image
    spec:
      automountServiceAccountToken: false
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: pdf2image
          image: ghcr.io/fjktkm/pdf2image:latest
          imagePullPolicy: Always
          env:
            - name: TOKEN
              valueFrom:
                secretKeyRef:
                  name: pdf2image
                  key: token
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /ready
              port: http
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: http
            periodSeconds: 20
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
              ephemeral-storage: 256Mi
            limits:
              cpu: "2"
              memory: 2Gi
              ephemeral-storage: 2Gi
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: true
          volumeMounts:
            - name: temporary-files
              mountPath: /tmp
      volumes:
        - name: temporary-files
          emptyDir:
            sizeLimit: 2Gi
