version: '3.8'
services:
  bot:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    env_file:
      - ../.env
    volumes:
      - ..:/workspace
    command: /bin/bash -c "while true; do sleep 1000; done"
