version: '3.8'
services:
  bot:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
      target: development
    env_file:
      - ../.env
    volumes:
      - ..:/workspaces/pdf2img
    ports:
      - "3000:3000"
    command: /bin/bash -c "while true; do sleep 1000; done"
