# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - pdf2imageDiscordBot

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js version
        uses: actions/setup-node@v1
        with:
          node-version: "18.x"

      - name: Cache npm dependencies
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.OS }}-npm-${{ hashFiles('package-lock.json') }}
          restore-keys: ${{ runner.OS }}-npm-

      - name: Install npm dependencies
        run: npm install

      # 必要なファイルだけをビルドディレクトリにコピー
      - name: Prepare files for deployment
        run: |
          New-Item -ItemType Directory -Force -Path build
          Copy-Item -Path commands, events, index.js, deploy-commands.js, ecosystem.config.js, package.json, package-lock.json -Destination build -Recurse

      # ビルドディレクトリだけをアップロード
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: node-app
          path: build

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: "Production"
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: node-app

      - name: Cache npm dependencies
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.OS }}-npm-${{ hashFiles('package-lock.json') }}
          restore-keys: ${{ runner.OS }}-npm-

      - name: Install npm dependencies
        run: npm install

      - name: "Deploy to Azure Web App"
        uses: azure/webapps-deploy@v2
        id: deploy-to-webapp
        with:
          app-name: "pdf2imageDiscordBot"
          slot-name: "Production"
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_C140FD55D98F4FD2B66EBB60809FAFB3 }}
          package: .
