# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - pdf2imageDiscordBot

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_b81dbcfdf8964cf489680018a9e41e43 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_ad26ed14809b4531941fa65645059948 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_b81dbcfdf8964cf489680018a9e41e43 }}/pdf2image:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'pdf2imageDiscordBot'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_b0248601b6d34952952b3d72ac5598c7 }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_b81dbcfdf8964cf489680018a9e41e43 }}/pdf2image:${{ github.sha }}'